### ISSUE TITLE
Refresh token

### ISSUE THREAD

**Issue by goowikns** [nullx27/eveonline-socialite#1]
How do you get the refresh token?

It seems to be null when retrieving $user->refreshToken

**Comment by Paic** [comment]
If I remember correctly, you need to request at least one scope to receive a refresh_token from the CCP OAuth server.

Be aware that eveonline-socialite (and Socialite in general) do not handle refresh_token completly and you'll need to do some manual work to get a new token from the refresh one.

**Comment by nullx27** [comment]
This is correct, you need to have at least one scope added to be issued a refresh token. Also socialite can not request new access tokens from your refresh tokens, so you need to have custom code to handle that.
