### ISSUE TITLE
Do not forget to release new commits!

### ISSUE THREAD

**Issue by ghost** [nullx27/eveonline-socialite#3]
Current build in packagist comes with errors.
```
[Symfony\Component\Debug\Exception\FatalThrowableError]
  Class 'nullx27\Socialite\EveOnline\EveOnlineServiceProvider' not found
```
In github is proper version.

Please update the release and packagist version!

**Comment by The1NdNly** [comment]
Got the same issue, found a fix?

even if i install with git i get the same issue.

```
"repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/nullx27/eveonline-socialite.git"
        }
    ],
```

**Comment by ghost** [comment]
nullx27\Socialite\EveOnline\ **Providers** \EveOnlineServiceProvider

**Comment by The1NdNly** [comment]
i'm a bit new to this, could you give me a idiots 1, 2, 3 please?
ive tried using the latest git commit with the updated paths, i also tried manually including with no luck. i feel a bit stupid at this point tbh..

**Comment by matthewpennell** [comment]
Same problems here.

@necrotex, can you please update the public release?

For anyone else, it can be fixed by forcing the `dev-master` tag in your composer.json:

`"nullx27/eveonline-socialite": "dev-master"`

**Comment by nullx27** [comment]
Oh shit, I completely forgot about that. I'll make a release and update the docs.

**Comment by nullx27** [comment]
Updated the docs and published a new release.
